Refinitiv/refinitiv-ui

packages/core/src/events/TapEvent.ts

Tap event should use composed path to fire click events correctly

fix(core): tap event is not fired for Enter/Space inside ShadowDom

---

README.md

Updates readme to point to ui.refinitiv.com instead of PPE CDN

docs(readme): point to ui.refinitiv.com

---

packages/elements/package.json

Changes homepage on npm to point to documentation site instead of GitHub readme

chore(elements): update homepage on npm

---

packages/elements/src/button/__test__/button.test.js
packages/elements/src/checkbox/__test__/checkbox.test.js
packages/elements/src/radio-button/__test__/radio-button.test.js
packages/elements/src/toggle/__test__/toggle.test.js

Removes useless async/await before a11y test assertion.
Code improvement

refactor: remove await from a11y test assertion

---

packages/core/__test__/events/TapEvent.test.js
packages/core/__test__/registries/NativeStyleRegistry.test.js
packages/core/src/events/TapEvent.ts

Tap event may be fired on wrong target on `space` key.

fix(core): tap event may be fired on wrong target on `space` key

---

packages/elements/src/tree/__test__/tree.test.js
packages/elements/src/tree/managers/tree-manager.ts

Correctly updates dependant item chacked states, when managing relationships.

fix(tree): correctly update dependant checked states

---

.github/workflows/release.yml

- Change usage of release process from `lerna publish` to `lerna publish from-git`
- add refinitiv-ci-dev's token for permission in release process
Fixes # (issue)

fix: add token for ci release

---

packages/elemental-theme/src/custom-elements/ef-clock.less

Make digital part inside analog clock to use font close to UX spec (from 9px -> ~10px).

fix(clock): slightly increase font size of digital part inside analog clock

---

packages/phrasebook/src/locale/ja/tree-select.ts

The change is related to the syntax of the ICU message that requires `other` argument.
Fixes # (issue)
ELF-1680  Japanese translation (ja) in tree-select does not work

fix(phrasebook): change ICU syntax on japanese language

---

packages/elements/src/combo-box/__test__/combo-box.interaction.test.js
packages/elements/src/combo-box/index.ts

Found an incorrect import in combo-box. After merging Lit2, it reverted to import pill. It should import counter.
Fixes # (issue)

fix(combo-box): import counter instead of pill

---

packages/elemental-theme/src/custom-elements/ef-tree-item.less
packages/halo-theme/src/custom-elements/ef-tree-item.less
packages/solar-theme/src/custom-elements/ef-tree-item.less

I managed to reduce the horizontal padding to 0px and let the margin of the checkbox manage the space between the checkbox and label.  When there is an icon on items, I need to add space between icon and label. This fixed effect on tree-select and tree.
Fixes # (issue)
ELF-1678 the space between checkbox and label is too large

fix(tree-item): reduce space between checkbox and label

---

packages/elements/src/autosuggest/index.ts

Missing jsdoc for slot content in Autosuggest so it doesn't generate slot section in the API docs.

docs(autosuggest): add missing jsdoc for slot content

---

packages/elements/src/datetime-picker/index.ts

Fix typo in jsdoc for slot so it doesn't generate slot in API section

docs(datetime-picker): fix typo jsdoc for slot content

---

scripts/release/api-analyzer.js

Elf-docs use `custom-elements.md` files that generated by `api-analyzer` script and some column in the files are missing some value and have some unnecessary column so we need to modified it. 
- Remove readonly modifier form meta data of properties ( Still keeps static modifier )
- Convert default value of some properties that defined by `@default` syntax
- Merge attributes that defined by JSDOC to properties table
---------

chore: remove modifier and merge attribute column on generated api docs

---

packages/solar-theme/src/custom-elements/ef-tree-item.less

This fixed was related to this PR [fix(tree-item): reduce space between checkbox and label](https://github.com/Refinitiv/refinitiv-ui/pull/93). I was missed to add some of the margin of part checkbox on the solar theme. 
Fixes # ELF-1678

fix(tree-item): slightly increase margin the part checkbox on solar theme

---

packages/core/__snapshots__/elements/FormFieldElement/AriaDescriptionTest.md
packages/core/__snapshots__/elements/FormFieldElement/AriaLabelTest.md
packages/core/__snapshots__/elements/FormFieldElement/DefaultsTest.md
packages/core/__snapshots__/elements/FormFieldElement/DisabledTest.md
packages/core/__snapshots__/elements/FormFieldElement/ErrorTest.md
packages/core/__snapshots__/elements/FormFieldElement/PlaceholderTest.md
packages/core/__snapshots__/elements/FormFieldElement/ReadonlyTest.md
packages/core/__snapshots__/elements/FormFieldElement/RequiredTest.md
packages/core/src/elements/FormFieldElement.ts
packages/elements/src/color-dialog/__snapshots__/ColorDialog.md
packages/elements/src/combo-box/__snapshots__/AsyncFilter.md
packages/elements/src/combo-box/__snapshots__/Filter.md
packages/elements/src/combo-box/__snapshots__/Selected.md
packages/elements/src/combo-box/__snapshots__/Template.md
packages/elements/src/combo-box/__snapshots__/Value.md
packages/elements/src/datetime-picker/__snapshots__/DOMStructure.md
packages/elements/src/email-field/__snapshots__/EmailField.md
packages/elements/src/multi-input/__snapshots__/MultiInput.md
packages/elements/src/number-field/__snapshots__/NumberField.md
packages/elements/src/pagination/__snapshots__/Pagination.md
packages/elements/src/password-field/__snapshots__/PasswordField.md
packages/elements/src/search-field/__snapshots__/SearchField.md
packages/elements/src/text-field/__snapshots__/TextField.md
packages/elements/src/time-picker/__snapshots__/TimePicker.md
packages/elements/src/tree-select/__snapshots__/TreeSelect.md

It is wrong to have `aria-hidden` for focusable elements

refactor(core): remove aria-hidden and role from FormField element

---

packages/halo-theme/package.json

`import '@refinitiv-ui/halo-theme/dark/imports/native-elements';` does not work anymore because we don't export this path in package.json.
Error message is
```
Error: Module not found: Error: Package path ./dark/import/native-elements is not exported from package C:\Users\UC255417\w\angular13\node_modules\@refinitiv-ui\halo-theme (see exports field in C:\Users\UC255417\w\angular13\node_modules\@refinitiv-ui\halo-theme\package.json)
```
We should ensure that existing app who use import '@refinitiv-ui/halo-theme/dark/imports/native-elements'; won't break after upgrading to EF5.

fix(halo-theme): fix import native-element path

---

package-lock.json
tsconfig.json

`incremental` compiler option was introduced in [TS3.4](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#faster-subsequent-builds-with-the---incremental-flag). 
- This can reduces over 50% of build time on subsequent builds by using build information from `.tsbuildinfo`
- `.tsbuildinfo` should not be committed

chore: add incremental to TypeScript compiler option for faster subsequent builds

---

packages/core/.npmignore

Ignore release scripts when publish to NPM 
You can test this by running `npm publish --dry-run` scripts should not be on filelist.

fix: release script should not be publish to NPM

---

package-lock.json
packages/core/package.json
packages/polyfills/package.json
packages/translate/package.json

There seems to be an issue between `lit@2.1.0` and Skypack, see https://codepen.io/wsuwt/pen/bGoxPVw?editors=1011. This is to make sure that we use a patched lit version `2.1.1`.
Additionally, I think we could benefit from a new directive - `choose`, see https://lit.dev/docs/templates/directives/#choose.

feat: upgrade `lit` to 2.1.1

---

packages/elements/src/checkbox/__test__/checkbox.test.js
packages/elements/src/checkbox/index.ts
packages/elements/src/radio-button/__test__/radio-button.test.js
packages/elements/src/radio-button/index.ts

See, 
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio
Native checkbox and radio button can only be toggle via `Space` key.

fix: `Enter` should not check/uncheck radio and checkbox

---

packages/elements/src/radio-button/__test__/radio-button.test.js
packages/elements/src/radio-button/index.ts

Adds `IE11` arrow keys navigation support.

fix(radio-button): add IE11 arrow keys navigation support

---

packages/halo-theme/src/custom-elements/ef-tree-select.less

Default width of inner panel in Tree Select is too small so x-scrollbar. 
Fixes # ELF-1305

fix(tree-select): remove unnecessary x-scrollbar on default styles

---

packages/halo-theme/src/shared-styles/checkbox.less

When hover at the end of checkbox label, it shows wrong cursor style. Cursor pointer should only use when hover on the tick box. Same problem with radio button.
Fixes # ELF-1648

fix(checkbox): wrong cursor style when hover the end of checkbox label

---

packages/elemental-theme/src/custom-elements/ef-collapse.less
packages/elements/src/collapse/__snapshots__/Collapse.md
packages/elements/src/collapse/index.ts

Reverts Refinitiv/refinitiv-ui#161
@Sakchai-Refinitiv this should be reviewed properly by members of the team with deeper accessibility knowledge.

Revert "feat(collapse): support screen reader"

---

package-lock.json
packages/core/package.json

Lit v2.1.3 breaks on SkyPack CDN.
ref: https://github.com/skypackjs/skypack-cdn/issues/255
Fix Lit to v2.1.2 for now, otherwise, demo block on Doc won't work.

fix: fix lit to v2.1.2 as v2.1.3 has issue with SkyPack

---

package-lock.json
packages/elements/src/overlay/elements/overlay.ts
packages/polyfills/package.json
packages/translate/package.json

Lit v2.1.3 breaks on SkyPack CDN.
ref: https://github.com/skypackjs/skypack-cdn/issues/255
Fix Lit to v2.1.2 for now, otherwise, demo block that has element with translation on Doc won't work.

Fix/fix lit version to 2.1.2 in translate and polyfills package
